import os
import uuid
import json
import subprocess
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# Use absolute paths based on the location of main.py
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Adjusted to point to the Compiler-Design folder one level up
COMPILER_EXE = os.path.abspath(os.path.join(BASE_DIR, "..", "Compiler-Design", "my_compiler.exe"))
TEMP_DIR = os.path.abspath(os.path.join(BASE_DIR, "temp_workspace"))

if not os.path.exists(TEMP_DIR):
    os.makedirs(TEMP_DIR)

@app.route('/api/compile', methods=['POST'])
def compile_phases():
    data = request.json
    source_code = data.get('code', '')

    if not source_code:
        return jsonify({"success": False, "error": "Code is empty"}), 400

    req_id = str(uuid.uuid4())
    input_f = os.path.join(TEMP_DIR, f"in_{req_id}.c")
    tok_f = os.path.join(TEMP_DIR, f"tok_{req_id}.json")
    ast_f = os.path.join(TEMP_DIR, f"ast_{req_id}.json")
    sem_f = os.path.join(TEMP_DIR, f"sem_{req_id}.json")

    try:
        with open(input_f, 'w') as f:
            f.write(source_code)

        # Check if EXE exists before running to avoid crash
        if not os.path.exists(COMPILER_EXE):
            return jsonify({"success": False, "error": f"Compiler not found at {COMPILER_EXE}"}), 500

        process = subprocess.run(
            [COMPILER_EXE, input_f, tok_f, ast_f, sem_f],
            capture_output=True, text=True, timeout=10
        )

        response = {
            "success": True,
            "compiler_logs": process.stdout,
            "lexical": None, "syntax": None, "semantic": None
        }

        # Read JSON outputs generated by main.cpp
        if os.path.exists(tok_f):
            with open(tok_f, 'r') as f: response["lexical"] = json.load(f)
        if os.path.exists(ast_f):
            with open(ast_f, 'r') as f: response["syntax"] = json.load(f)
        if os.path.exists(sem_f):
            with open(sem_f, 'r') as f: response["semantic"] = json.load(f)

        if process.returncode != 0:
            response["success"] = False
            response["error"] = process.stderr or "Compiler error"

        return jsonify(response)

    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500
    finally:
        for f in [input_f, tok_f, ast_f, sem_f]:
            if os.path.exists(f): os.remove(f)

if __name__ == '__main__':
    app.run(debug=True, port=5000)